apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
data:
  azurestorageaccountname: "{{ .Values.storage.accountName | b64enc }}"
  azurestorageaccountkey: "{{ .Values.storage.accountKey | b64enc }}"