apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-devops-agent
  namespace: azdo
data:
  AZP_URL: "{{ regexReplaceAll "\\/$" .Values.linux.azureDevOps.orgUrl "" }}"
  AZP_POOL: "{{ .Values.linux.azureDevOps.poolName }}"