apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: AZP_URL
          valueFrom:
            configMapKeyRef:
              key: AZP_URL
              name: azdevops-agent
        - name: AZP_POOL
          valueFrom:
            configMapKeyRef:
              key: AZP_POOL
              name: azdevops-agent
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azdevops-agent
              key: AZP_TOKEN
      {{- if .Values.env.values -}}
      {{- range .Values.env.values }}
        - name: {{ .name }}
          value: {{ .value | quote }}
      {{- end -}}
      {{- end }}
        - name: PIPELINE_DEMO_JOB_CAPABILITY_AKS
          value: "{{ .Values.linux.azureDevOps.capability }}"
        volumeMounts:
        - mountPath: /mnt/diag
          name: azure
      volumes:
      - name: azure
        persistentVolumeClaim:
          claimName: azurefile
