trigger:
 - main

schedules:
- cron: '0 0 * * *'
  displayName: 'Daily build (0:00 UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'dockeragent'
  tags: 'latest'
  scriptDirectory: '$(Build.SourcesDirectory)/scripts'

steps:
# - task: Docker@2
#   displayName: Build image
#   inputs:
#     repository: $(imageName)
#     tags: '$(tags)'
#     command: build
#     Dockerfile: images/ubuntu/Dockerfile
- pwsh: |
    ./build_image.ps1
  displayName: Build image
  workingDirectory: '$(scriptDirectory)'
