trigger:
 - main

schedules:
- cron: '0 0 * * *'
  displayName: 'Daily build (0:00 UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  containerRegistry: 'ericvanacr'
  imageName: 'dockeragent'
  tags: 'latest'
  scriptDirectory: '$(Build.SourcesDirectory)/scripts'

steps:
# - pwsh: |
#     ./build_image.ps1
#   displayName: Build image
#   workingDirectory: '$(scriptDirectory)'
- task: Docker@2
  displayName: Push image
  inputs:
    command: buildAndPush
    containerRegistry: '$(containerRegistry)'
    Dockerfile: images/ubuntu/Dockerfile
    repository: $(imageName)
    tags: |
      $(Build.BuildId)
      latest    
