parameters:
- name: imageTag
  displayName: Image tag
  type: string
  default: latest

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ parameters.imageTag }}-$(Build.BuildId)
  
trigger: none

schedules:
- cron: '0 0 * * Thu'
  displayName: 'Daily build (0:00 UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

variables:
- group: 'build-container-agent-image' # shared with deploy-container-agents.yml

jobs:
- template: build-image-template.yml
  parameters:
    name: build
    displayName: Build images
    imageTag: ${{ parameters.imageTag }}

- template: image-info-template.yml
  parameters:
    name: test
    dependsOn: build
    displayName: Test agent tools image
    imageTag: $(Build.BuildId)