trigger: none

schedules:
- cron: '0 0 * * Thu'
  displayName: 'Daily build (0:00 UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
- group: 'build-container-agent-image' # shared with deploy-container-agents.yml
# should contain 'containerRegistry' -> name of Container Registry Service Connection
- name: date
  value: $[format('{0:yyyyMMdd}', pipeline.startTime)]
- name: 'tags'
  value: 'latest'
- name: 'imageName'
  value: 'pipelineagent/ubuntu'
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/scripts'

steps:
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    containerRegistry: '$(containerRegistry)'
    repository: $(imageName)
    tags: |
      latest
      $(date)

- task: Docker@2
  displayName: Push image
  inputs:
    command: push
    containerRegistry: '$(containerRegistry)'
    repository: $(imageName)
    tags: |
      latest
      $(date)