parameters:
- name: imageTag
  displayName: Image tag
  type: string
  default: latest
  
trigger: none

schedules:
- cron: '0 0 * * Thu'
  displayName: 'Daily build (0:00 UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
- group: 'build-container-agent-image' # shared with deploy-container-agents.yml
# should contain 'containerRegistry' -> name of Container Registry Service Connection
- name: date
  value: $[format('{0:yyyyMMdd}', pipeline.startTime)]
- name: 'tags'
  value: 'latest'
- name: 'baseImageName'
  value: 'pipelineagent/ubuntu'
- name: 'agentImageName'
  value: 'pipelineagent/ubuntu-agent'
- name: 'imageTag'
  value: ${{ parameters.imageTag }}
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/scripts'

steps:
- task: Docker@2
  displayName: Build base image
  inputs:
    command: build
    containerRegistry: '$(containerRegistry)'
    Dockerfile: 'images/ubuntu/Dockerfile'
    repository: $(baseImageName)
    tags: |
      $(imageTag)
      $(date)
      $(Build.SourceBranchName)

- task: Docker@2
  displayName: Push base image
  inputs:
    command: push
    containerRegistry: '$(containerRegistry)'
    repository: $(baseImageName)
    tags: |
      $(imageTag)
      $(date)
      $(Build.SourceBranchName)

- task: Docker@2
  displayName: Build agent image
  inputs:
    arguments: '--build-arg BASE_IMAGE=$(containerRegistry).azurecr.io/$(baseImageName) --quiet'
    command: build
    containerRegistry: '$(containerRegistry)'
    Dockerfile: 'images/ubuntu-agent/Dockerfile'
    repository: $(agentImageName)
    tags: |
      $(imageTag)
      $(date)
      $(Build.SourceBranchName)

- task: Docker@2
  displayName: Push agent image
  inputs:
    command: push
    containerRegistry: '$(containerRegistry)'
    repository: $(agentImageName)
    tags: |
      $(imageTag)
      $(date)
      $(Build.SourceBranchName)

