parameters:
- name: imageTag
  displayName: Image tag
  type: string
  default: latest
  
trigger: none

schedules:
- cron: '0 0 * * Thu'
  displayName: 'Daily build (0:00 UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

variables:
- group: 'build-container-agent-image' # shared with deploy-container-agents.yml
# should contain 'containerRegistry' -> name of Container Registry Service Connection
- name: date
  value: $[format('{0:yyyyMMdd}', pipeline.startTime)]
- name: 'tags'
  value: latest
- name: 'agentImageName'
  value: pipelineagent/ubuntu-agent
- name: 'toolsImageName'
  value: pipelineagent/ubuntu
- name: 'toolsImageFQName'
  value: $(containerRegistry).azurecr.io/$(toolsImageName):$(Build.BuildId)
- name: 'imageTag'
  value: ${{ parameters.imageTag }}
- name: 'scriptDirectory'
  value: $(Build.SourcesDirectory)/scripts

jobs:
- job: build
  displayName: Build images
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Docker@2
    displayName: Build tools image
    inputs:
      command: build
      containerRegistry: '$(containerRegistry)'
      Dockerfile: 'images/ubuntu/Dockerfile'
      repository: $(toolsImageName)
      tags: |
        $(imageTag)
        $(date)
        $(Build.BuildId)
        $(Build.SourceBranchName)

  - task: Docker@2
    displayName: Push tools image
    inputs:
      command: push
      containerRegistry: '$(containerRegistry)'
      repository: $(toolsImageName)
      tags: |
        $(imageTag)
        $(date)
        $(Build.BuildId)
        $(Build.SourceBranchName)

  - task: Docker@2
    displayName: Build agent image
    inputs:
      arguments: '--build-arg BASE_IMAGE=$(toolsImageFQName)'
      command: build
      containerRegistry: '$(containerRegistry)'
      Dockerfile: 'images/ubuntu-agent/Dockerfile'
      repository: $(agentImageName)
      tags: |
        $(imageTag)
        $(date)
        $(Build.SourceBranchName)

  - task: Docker@2
    displayName: Push agent image
    inputs:
      command: push
      containerRegistry: '$(containerRegistry)'
      repository: $(agentImageName)
      tags: |
        $(imageTag)
        $(date)
        $(Build.SourceBranchName)

- template: image-info-template.yml
  parameters:
    name: test
    dependsOn: build
    imageTag: $(Build.BuildId)