trigger:
 - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'dockeragent'
  tags: 'latest'

steps:
- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    tags: '$(tags)'
    command: build
    Dockerfile: images/ubuntu/Dockerfile