parameters:
# Test auto-scaling by setting sleep time
- name: numberOfJobs
  displayName: Number of parallel jobs
  type: number
  default: 1
- name: sleepTimeMinutes
  displayName: Sleep time in minutes
  type: number
  default: 0
  
trigger: none

variables:
  pool: 'Container Agents'

jobs:
- job: createStrategy
  displayName: Create Strategy
  steps:
  - pwsh: |
      $hash = @{}
      for ($i=0; $i -lt ${{ parameters.numberOfJobs }}; $i++) {
        $hash.Add("job${i}",@{"index"=$i})
      }
      $hash | ConvertTo-Json | Set-Variable strategy
      Write-Host "##vso[task.setvariable variable=strategy;isOutput=true]$strategy"
    name: pwsh
    displayName: 'Create srategy JSON'
- job: ubuntu
  dependsOn: createStrategy
  strategy:
    matrix: $[ dependencies.createStrategy.outputs['pwsh.strategy'] ]
  displayName: Create Strategy
  pool:
    name: $(pool)
    demands:
    - agent.os -equals Linux
  steps:
  - bash: |
      echo Hello from Ubuntu
      lsb_release -d
    displayName: 'Ubuntu info'
  - pwsh: |
      az -v
    displayName: 'Azure CLI info'
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
    displayName: 'PowerShell info'
  - pwsh: |
      terraform -v
    displayName: 'Terraform info'
  - ${{ if gt(parameters.sleepTimeMinutes, 0) }}:
    - pwsh: |
        Start-Sleep -Duration (New-TimeSpan -Minutes ${{ parameters.sleepTimeMinutes }})
      displayName: 'Sleep ${{ parameters.sleepTimeMinutes }} minutes'
