parameters:
# Test auto-scaling by setting sleep time
- name: sleepTimeMinutes
  displayName: Sleep time in minutes
  type: int
  default: 0
  
trigger: none

variables:
  pool: 'Container Agents'

jobs:
- job: ubuntu
  pool:
    name: $(pool)
    demands:
    - agent.os -equals Linux
  steps:
  - bash: |
      echo Hello from Ubuntu
      lsb_release -d
    displayName: 'Ubuntu info'
  - pwsh: |
      az -v
    displayName: 'Azure CLI info'
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
    displayName: 'PowerShell info'
  - pwsh: |
      terraform -v
    displayName: 'Terraform info'
  - ${{ if gt(parameters.sleepTimeMinutes, 0) }}:
    - pwsh: |
        Start-Sleep -Seconds (New-TimeSpan -Minutes ${{ parameters.sleepTimeMinutes }})
      displayName: 'Sleep ${{ parameters.sleepTimeMinutes }} minutes'
