name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)
pr: none
schedules:
- cron: '0 0 * * *'
  displayName: 'Daily build (0:00 UTC)'
  # Run when there are no changes
  always: 'true'
  branches:
    include:
    - main
trigger: none

variables:
# - group: 'build-container-agent-image' # shared with deploy-container-agents.yml
# should contain 'containerRegistry', 'containerRegistryConnection' -> name of Container Registry Service Connection
# - name: 'containerRegistry'
#   value: 'ericvanimages'
# - name: 'containerRegistryConnection'
#   value: 'ericvanimages'
- name: 'tags'
  value: 'latest'
- name: 'imageName'
  value: 'pipelineagent/ubuntu'
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/scripts'
- name: 'vmImage'
  value: ubuntu-latest

jobs:
- job: ubuntuContainer
  displayName: Container job
  container:
    # image: $(containerRegistry).azurecr.io/$(imageName):$(tags)
    # endpoint: ${{ variables.containerRegistryConnection }}
    image: ericvanimages.azurecr.io/pipelineagent/ubuntu:latest
    endpoint: ericvanimages
  pool:
    name: Azure Pipelines
    vmImage: $(vmImage)
  steps:
  - bash: |
      echo Hello from Ubuntu
      lsb_release -d
    displayName: 'Ubuntu info'
  - pwsh: |
      az -v
    displayName: 'Azure CLI info'
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
      Get-InstalledModule | Sort-Object -Property Name
    displayName: 'PowerShell info'
  - pwsh: |
      terraform -v
    displayName: 'Terraform info'
