name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-$(Build.BuildId)
parameters:
- name: azureServiceConnection
  displayName: Azure Service Connection
  type: string
  default: my-azure-subscription
- name: containerEndpoint
  displayName: Docker Service Connection
  type: string
  default: containerEndpoint
pr: none
schedules:
- cron: '0 0 * * *'
  displayName: 'Daily build (0:00 UTC)'
  # Run when there are no changes
  always: 'true'
  branches:
    include:
    - main
trigger: none

jobs:
- template: image-info-template.yml
  parameters:
    name: test
    azureServiceConnection: ${{ parameters.azureServiceConnection }}
    containerEndpoint: ${{ parameters.containerEndpoint }}
