# This pipeline is for CI/CD
parameters:
- name: workspace
  displayName: Terraform Workspace
  type: string
  default: ci
  values:
  - ci
  - cd
  - cd1
  - cd2
  - cd3
  - cd3
  - test
  - test1
  - test2
  - test3

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ parameters.workspace }}-$(Build.BuildId)

trigger: none

pr:
  autoCancel: false
  branches:
    include:
    - '*'
  drafts: false
  paths:
    exclude:
    - '.devcontainer/**'  
    - 'visuals/**'  
    - '*.md'  

schedules:
- cron: '0 0 * * Mon,Thu'
  displayName: 'Bi-weekly build (UTC)'
  # Run if there are no changes
  always: 'true'
  branches:
    include:
    - main

variables:
- name: AZURE_CORE_ONLY_SHOW_ERRORS
  value: 'true'
- name: AZURE_EXTENSION_USE_DYNAMIC_INSTALL
  value: 'yes_without_prompt'
- name: 'imageRepository'
  value: 'pipelineagent/ubuntu-agent'
- name: 'pool'
  value: 'Azure Pipelines'
- name: 'identityScriptDirectory'
  value: '$(Build.SourcesDirectory)/scripts/identity/scripts/azure-devops'
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/scripts'
- name: 'terraformDirectory'
  value: '$(Build.SourcesDirectory)/terraform'
- name: 'TF_IN_AUTOMATION'
  value: 'true'
- name: 'TF_INPUT'
  value: 0
- name: 'TF_WORKSPACE'
  value: '${{ parameters.workspace }}'
- name: 'vmImage'
  value: 'ubuntu-latest'
- group: 'pipeline-container-agents' # shared with terraform-ci.yml

jobs:    
- job: provision

  pool:
    name: '$(pool)'
    vmImage: $(vmImage)

  steps:
  - checkout: self
    submodules: true

  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'latest'

  - task: AzureCLI@2
    displayName: 'Terraform init'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Copy-Item backend.tf.sample backend.tf
        terraform init -backend-config="container_name=$(TF_STATE_BACKEND_STORAGE_CONTAINER_NAME)" `
                       -backend-config="key=terraform.tfstate" `
                       -backend-config="resource_group_name=$(TF_STATE_BACKEND_RESOURCE_GROUP_NAME)" `
                       -backend-config="storage_account_name=$(TF_STATE_BACKEND_STORAGE_ACCOUNT_NAME)" `
                       -backend-config="client_id=${env:servicePrincipalId}" `
                       -backend-config="client_secret=${env:servicePrincipalKey}" `
                       -backend-config="oidc_token=${env:idToken}" `
                       -backend-config="subscription_id=$(az account show --query id -o tsv)" `
                       -backend-config="tenant_id=${env:tenantId}"
      addSpnToEnvironment: true
      failOnStandardError: true
      workingDirectory: '$(terraformDirectory)'
    env:
      ARM_USE_AZUREAD: true

  - task: AzureCLI@2
    name: terraformVariables
    displayName: 'Terraform output'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        terraform output
      failOnStandardError: true
      workingDirectory: '$(terraformDirectory)'
    env:
      ARM_USE_CLI: true

  - task: AzureCLI@2
    displayName: 'Select Terraform workspace'
    inputs:
      azureSubscription: '$(subscriptionConnection)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        # $(identityScriptDirectory)/set_terraform_azurerm_vars.ps1

        if ((terraform workspace list) -match "\W+$(TF_WORKSPACE)$") {
          Write-Host "Terraform workspace '$(TF_WORKSPACE)' already exists"
          terraform workspace select $(TF_WORKSPACE)
          terraform workspace select $(TF_WORKSPACE) 2>$null
        } else {
          Write-Host "Creating Terraform workspace '$(TF_WORKSPACE)'..."
          terraform workspace new $(TF_WORKSPACE)
          terraform workspace new $(TF_WORKSPACE) 2>$null
        }
        if ((terraform workspace show) -eq '$(TF_WORKSPACE)') {
          Write-Host "Terraform workspace '$(TF_WORKSPACE)' selected"
          exit 0
        } else {
          Write-Error "Terraform workspace '$(TF_WORKSPACE)' does not exist"
          exit 1
        } 
      useGlobalConfig: true
      failOnStandardError: true
      workingDirectory: '$(terraformDirectory)'
    env:
      ARM_USE_CLI: true